# Generated by Django 3.2.7 on 2021-10-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaransiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswauser',
            name='aggree',
            field=models.BooleanField(default=False),
        ),
    ]
