# Generated by Django 3.2.8 on 2021-10-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaransiswa', '0002_siswauser_aggree'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswauser',
            name='kelas',
            field=models.CharField(choices=[('10', 'sepuluh'), ('11', 'sebelas'), ('12', 'duabelas')], default='10', max_length=225),
        ),
        migrations.AddField(
            model_name='siswauser',
            name='mata_pelajaran',
            field=models.CharField(choices=[('MTK', 'Matematika'), ('Fis', 'Fisika'), ('Bio', 'Biologi'), ('Kim', 'Kimia'), ('B.Indo', 'B.Indonesia'), ('B.Ing', 'B.Inggris'), ('Eko', 'Ekonomi'), ('Geo', 'Geografi'), ('Sosio', 'Sosiologi'), ('Sejarah', 'Sejarah')], default=None, max_length=225),
        ),
        migrations.AddField(
            model_name='siswauser',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], default='Card', max_length=225),
        ),
    ]
