# Generated by Django 3.2.8 on 2021-10-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaransiswa', '0003_auto_20211025_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswauser',
            name='kelas',
            field=models.CharField(choices=[('1', '10'), ('2', '11'), ('3', '12')], default='10', max_length=225),
        ),
    ]
