# Generated by Django 3.2.8 on 2021-10-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaransiswa', '0004_alter_siswauser_kelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswauser',
            old_name='aggree',
            new_name='agree',
        ),
    ]
