<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-11-05 14:22
=======
# Generated by Django 3.2.8 on 2021-11-08 10:25
>>>>>>> 919197c4d02ee74392a4beaa937c5533618f4a48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selesai', models.DateField(blank=True, null=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
