# Generated by Django 3.2.8 on 2021-10-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggree', models.BooleanField(default=False)),
                ('kelas', models.CharField(choices=[('1', '10'), ('2', '11'), ('3', '12')], default='10', max_length=225)),
                ('mata_pelajaran', models.CharField(choices=[('MTK', 'Matematika'), ('Fis', 'Fisika'), ('Bio', 'Biologi'), ('Kim', 'Kimia'), ('B.Indo', 'B.Indonesia'), ('B.Ing', 'B.Inggris'), ('Eko', 'Ekonomi'), ('Geo', 'Geografi'), ('Sosio', 'Sosiologi'), ('Sejarah', 'Sejarah')], max_length=225)),
                ('validasi_guru', models.FileField(upload_to='')),
            ],
        ),
    ]
