# Generated by Django 3.2.8 on 2021-10-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuruUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('nomor_telefon', models.CharField(default='', max_length=100)),
                ('tanggal_lahir', models.DateField(default='1961-01-01')),
                ('jenis_kelamin', models.CharField(choices=[('p', 'pria'), ('w', 'wanita')], default='', max_length=100)),
                ('alamat', models.TextField(default='', max_length=140)),
                ('kelas', models.CharField(choices=[('1', '10'), ('2', '11'), ('3', '12')], default='10', max_length=225)),
                ('mata_pelajaran', models.CharField(choices=[('MTK', 'Matematika'), ('Fis', 'Fisika'), ('Bio', 'Biologi'), ('Kim', 'Kimia'), ('B.Indo', 'B.Indonesia'), ('B.Ing', 'B.Inggris'), ('Eko', 'Ekonomi'), ('Geo', 'Geografi'), ('Sosio', 'Sosiologi'), ('Sejarah', 'Sejarah')], max_length=225)),
                ('validasi_guru', models.FileField(upload_to='')),
                ('aggree', models.BooleanField(default=False)),
            ],
        ),
    ]
