# Generated by Django 3.2.8 on 2021-10-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaranguru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguru',
            name='alamat',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='userguru',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userguru',
            name='jenis_kelamin',
            field=models.CharField(choices=[('p', 'pria'), ('w', 'wanita')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userguru',
            name='nama_lengkap',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userguru',
            name='nomor_telefon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userguru',
            name='tanggal_lahir',
            field=models.DateField(default='1961-01-01'),
        ),
    ]
