# Generated by Django 3.2.9 on 2021-12-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testimoni',
            table='testimoni',
        ),
    ]
