# Generated by Django 3.2.9 on 2021-11-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20211104_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alamat',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
