# Generated by Django 3.2.8 on 2021-10-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20211030_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mata_pelajaran',
            field=models.CharField(default='anonymous', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], default='Card', max_length=225),
        ),
    ]
