# Generated by Django 3.2.8 on 2021-10-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20211031_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kelas',
            field=models.CharField(choices=[('1', '10'), ('2', '11'), ('3', '12')], default=10, max_length=225),
            preserve_default=False,
        ),
    ]
