# Generated by Django 3.2.9 on 2021-11-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_customuser_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alamat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
