# Generated by Django 3.2.8 on 2021-11-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_customuser_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('pria', 'pria'), ('wanita', 'wanita')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kelas',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12')], max_length=225),
        ),
    ]
